# Site settings
title: Also Known As "Jut"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The personal web site for Justin McMinn
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://akajut.com" # the base hostname & protocol for your site
twitter_username: akajut
github_username:  akajut

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
